- name: Install Python packages
  apt:
    name:
      - python3.9
      - virtualenv
    update_cache: yes

- name: Create Django server directory
  file:
    path: /srv/tournesol
    state: directory

- name: Create Virtualenv for dummy project
  pip:
    name:
      - Django
      - gunicorn
      - uvicorn
    virtualenv: /srv/tournesol/venv
    virtualenv_python: python3.9

- name: Create dummy Django project
  shell:
    chdir: /srv/tournesol
    cmd: . venv/bin/activate && django-admin startproject tournesol
    creates: /srv/tournesol/tournesol

- name: Create dummy Django app
  shell:
    chdir: /srv/tournesol/tournesol
    cmd: . ../venv/bin/activate && python manage.py startapp backend
    creates: /srv/tournesol/tournesol/backend

- name: Authorize any hostname in dummy app
  lineinfile:
    dest: /srv/tournesol/tournesol/tournesol/settings.py
    regexp: "^ALLOWED_HOSTS = "
    line: "ALLOWED_HOSTS = ['*']"

- name: Copy Nginx configuration
  copy:
    src: tournesol-nginx-conf
    dest: /etc/nginx/sites-available/tournesol
  notify: Reload Nginx

- name: Create Users
  user:
    name: gunicorn
    system: yes
    create_home: no

- name: Copy Gunicorn service file
  copy:
    src: gunicorn.service
    dest: /etc/systemd/system/gunicorn.service
  notify: Reload Gunicorn

- name: Copy Gunicorn socket file
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/gunicorn.socket

- name: Enable and start Gunicorn
  systemd:
    name: gunicorn.socket
    enabled: true
    state: started
    daemon_reload: true

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/tournesol
    dest: /etc/nginx/sites-enabled/tournesol
    state: link
  notify: Reload Nginx

- name: Create Django database
  postgresql_db:
    name: tournesol
  become: yes
  become_user: postgres

- name: Create Django database user
  postgresql_user:
    name: tournesol
    password: tournesol
    db: tournesol
  become: yes
  become_user: postgres

- name: Set database in Django settings
  replace:
    path: /srv/tournesol/tournesol/tournesol/settings.py
    after: "DATABASES = {\n    'default' = {\n"
    before: "\n    }\n}"
    regexp: "[.\n]+"
    replace: |
          'ENGINE': 'django.contrib.gis.db.backends.postgis',
          'NAME': 'tournesol',
          'USER': 'tournesol',
          'PASSWORD': 'tournesol',

- meta: flush_handlers
