all:
  children:
    tournesol:
      hosts:
        tournesol-vm:
          ansible_host: "192.168.122.242"
          # ansible_user: "jst"
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
